

[workspace]
resolver = "2"
exclude = ["zed-starlark"]
members = [
    "spaces/crates/spaces",
    "spaces/crates/starstd",
    "spaces/crates/spaces-utils",
]

[workspace.dependencies]
anyhow-source-location = "0.2.1"
anyhow = "1.0.95"
serde = { version = "1", features = ["derive", "rc"] }
starlark = { git = "https://github.com/facebook/starlark-rust", rev = "100f29bc1a57d344171a405e4e06bccc6b8b8e23"}
state = "0.6.0"
petgraph = "0.6.5"
serde_json = "1"
glob-match = "0.2.1"
url = "2.5.2"
toml = "0.9"
serde_yaml = "0.9"
strum = { version = "0.26", features = ["derive"] }

archiver = { package = "spaces-archiver", path = "./archiver", features = ["printer"] }
utils = { path = "spaces/crates/spaces-utils", package = "spaces-utils" }
printer = { package = "spaces-printer", path = "./printer" }
starstd.path = "spaces/crates/starstd"


[profile.dev]
opt-level = 3
lto = false
debug = true
strip = false
codegen-units = 16

[profile.release]
opt-level = "z"
lto = true
debug = false
panic = "abort"
strip = true
codegen-units = 1
