[package]
name = "changes"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
anyhow = "1"
walkdir = "2"
bincode = { version = "2.0.0-rc.3", features = ["derive"] }
glob-match = "0.2"

printer.workspace = true
anyhow-source-location.workspace = true
logger.workspace = true

