[package]
name = "lock"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
anyhow-source-location.workspace = true
printer.workspace = true
logger.workspace = true
