[package]
name = "copy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
reflink-copy = "0.1"
walkdir = "2"

anyhow-source-location.workspace = true
logger.workspace = true
printer.workspace = true